module SophiaService
  VERSION: String

  attr_accessor self.configuration: Configuration

  def self.configure: -> Configuration

  class ApiClient
    @sophia_routes: SophiaRoutes
    @sophia_user: String | nil
    @sophia_password: String | nil
    @sophia_token: String | nil
    @should_use_ssl: bool | nil
  end

  class Configuration
    @base_url: String
    @is_sophia_production: bool
    @sophia_password: String
    @sophia_user: String

    attr_reader base_url: String
    attr_reader is_sophia_production: bool
    attr_reader sophia_password: String
    attr_reader sophia_user: String
  end
end
